//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Resources.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPUWebPhet10.Resources.Application.Application", typeof(Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้ป้อนข้อมูลสถานศึกษา.
        /// </summary>
        public static string ERROR_MSG_01 {
            get {
                return ResourceManager.GetString("ERROR_MSG_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to มีข้อมูลโรงเรียนในระบบแล้ว.
        /// </summary>
        public static string ERROR_MSG_02 {
            get {
                return ResourceManager.GetString("ERROR_MSG_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้ป้อนที่อยู่.
        /// </summary>
        public static string ERROR_MSG_03 {
            get {
                return ResourceManager.GetString("ERROR_MSG_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาป้อนเฉพาะตัวเลข.
        /// </summary>
        public static string ERROR_MSG_04 {
            get {
                return ResourceManager.GetString("ERROR_MSG_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้ป้อนเบอร์ติดต่อ.
        /// </summary>
        public static string ERROR_MSG_05 {
            get {
                return ResourceManager.GetString("ERROR_MSG_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบอีเมลล์ไม่ถูกต้อง.
        /// </summary>
        public static string ERROR_MSG_06 {
            get {
                return ResourceManager.GetString("ERROR_MSG_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้ป้อนอีเมล์.
        /// </summary>
        public static string ERROR_MSG_07 {
            get {
                return ResourceManager.GetString("ERROR_MSG_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมลล์นี้มีผู้ใช้งานแล้ว.
        /// </summary>
        public static string ERROR_MSG_08 {
            get {
                return ResourceManager.GetString("ERROR_MSG_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาป้อนเฉพาะตัวเลข.
        /// </summary>
        public static string ERROR_MSG_09 {
            get {
                return ResourceManager.GetString("ERROR_MSG_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้เลือกประเภทสถานศึกษา.
        /// </summary>
        public static string ERROR_MSG_10 {
            get {
                return ResourceManager.GetString("ERROR_MSG_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้เลือกจังหวัด.
        /// </summary>
        public static string ERROR_MSG_11 {
            get {
                return ResourceManager.GetString("ERROR_MSG_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้เลือกอำเภอ.
        /// </summary>
        public static string ERROR_MSG_12 {
            get {
                return ResourceManager.GetString("ERROR_MSG_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ได้เลือกตำบล.
        /// </summary>
        public static string ERROR_MSG_13 {
            get {
                return ResourceManager.GetString("ERROR_MSG_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียน.
        /// </summary>
        public static string LB_BUTTON_01 {
            get {
                return ResourceManager.GetString("LB_BUTTON_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไขข้อมูล.
        /// </summary>
        public static string LB_BUTTON_02 {
            get {
                return ResourceManager.GetString("LB_BUTTON_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (เพิ่ม).
        /// </summary>
        public static string LB_BUTTON_04 {
            get {
                return ResourceManager.GetString("LB_BUTTON_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ลบข้อมูล).
        /// </summary>
        public static string LB_BUTTON_05 {
            get {
                return ResourceManager.GetString("LB_BUTTON_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใบสมัครการแข่งขันภาษาจีนเพชรยอดมงกุฏ .
        /// </summary>
        public static string LB_HEADER {
            get {
                return ResourceManager.GetString("LB_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลสถานศึกษา.
        /// </summary>
        public static string LB_LEGEND_1 {
            get {
                return ResourceManager.GetString("LB_LEGEND_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ครู/อาจารย์ผู้ควบคุมดูแลนักเรียน/นักศึกษา.
        /// </summary>
        public static string LB_LEGEND_2 {
            get {
                return ResourceManager.GetString("LB_LEGEND_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายชื่อนักเรียน/นักศึกษาที่สมัครแข่งขัน.
        /// </summary>
        public static string LB_LEGEND_3 {
            get {
                return ResourceManager.GetString("LB_LEGEND_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        public static string LB_LEGEND_4 {
            get {
                return ResourceManager.GetString("LB_LEGEND_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ไม่ต้องกรอกคำว่าโรงเรียน / มหาวิทยาลัย).
        /// </summary>
        public static string REGISETER_VALIDATE_MSG01 {
            get {
                return ResourceManager.GetString("REGISETER_VALIDATE_MSG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ (*) ต้องกรอกข้อมูล.
        /// </summary>
        public static string REGISTER_ITEM_REMARK_1 {
            get {
                return ResourceManager.GetString("REGISTER_ITEM_REMARK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string REGISTER_ITEM_REMARK_2 {
            get {
                return ResourceManager.GetString("REGISTER_ITEM_REMARK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ครู/อาจารย์ผู้ควบคุมดูแลนักเรียน/นักศึกษา.
        /// </summary>
        public static string REGISTER_ITEM001 {
            get {
                return ResourceManager.GetString("REGISTER_ITEM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลงทะเบียนเข้าใช้ระบบ.
        /// </summary>
        public static string REGISTER_ITEM016 {
            get {
                return ResourceManager.GetString("REGISTER_ITEM016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานศึกษาต้องเก็บ Username/Password ดังกล่าวไว้เป็นความลับเพื่อเข้าใช้ระบบในการแก้ไขข้อมูลการสมัคร /ส่งเอกสารยืนยันการสมัครแข่งขัน พร้อมแนบไฟล์เอกสารใบสมัครที่ลงนามโดยผู้บริหารสถานศึกษา.
        /// </summary>
        public static string REGISTER_ITEM017 {
            get {
                return ResourceManager.GetString("REGISTER_ITEM017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้าชื่อ(*).
        /// </summary>
        public static string REGISTER_STAFF_ITEM001 {
            get {
                return ResourceManager.GetString("REGISTER_STAFF_ITEM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ(*).
        /// </summary>
        public static string REGISTER_STAFF_ITEM002 {
            get {
                return ResourceManager.GetString("REGISTER_STAFF_ITEM002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล(*).
        /// </summary>
        public static string REGISTER_STAFF_ITEM003 {
            get {
                return ResourceManager.GetString("REGISTER_STAFF_ITEM003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์(*).
        /// </summary>
        public static string REGISTER_STAFF_ITEM004 {
            get {
                return ResourceManager.GetString("REGISTER_STAFF_ITEM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับชั้น(*).
        /// </summary>
        public static string REGISTER_STAFF_ITEM005 {
            get {
                return ResourceManager.GetString("REGISTER_STAFF_ITEM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระดับชั้น(*).
        /// </summary>
        public static string REGISTER_STUDENT_ITEM001 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปีที่(*).
        /// </summary>
        public static string REGISTER_STUDENT_ITEM002 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำนำหน้าชื่อ(*).
        /// </summary>
        public static string REGISTER_STUDENT_ITEM003 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ(*).
        /// </summary>
        public static string REGISTER_STUDENT_ITEM004 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล(*).
        /// </summary>
        public static string REGISTER_STUDENT_ITEM005 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์(*).
        /// </summary>
        public static string REGISTER_STUDENT_ITEM006 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล์.
        /// </summary>
        public static string REGISTER_STUDENT_ITEM007 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันเดือนปีเกิด.
        /// </summary>
        public static string REGISTER_STUDENT_ITEM008 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สัญชาติ.
        /// </summary>
        public static string REGISTER_STUDENT_ITEM009 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่น ๆ.
        /// </summary>
        public static string REGISTER_STUDENT_ITEM010 {
            get {
                return ResourceManager.GetString("REGISTER_STUDENT_ITEM010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งอยู่เลขที่ (*).
        /// </summary>
        public static string SCHOOL_ADDR {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เขต/อำเภอ (*).
        /// </summary>
        public static string SCHOOL_ADDR_AMPHUR {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR_AMPHUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรสาร.
        /// </summary>
        public static string SCHOOL_ADDR_FAX {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR_FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โทรศัพท์ (*).
        /// </summary>
        public static string SCHOOL_ADDR_PHONE {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จังหวัด(*).
        /// </summary>
        public static string SCHOOL_ADDR_PROVINCE {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถนน.
        /// </summary>
        public static string SCHOOL_ADDR_ROAD {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR_ROAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตรอก/ซอย .
        /// </summary>
        public static string SCHOOL_ADDR_SOI {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR_SOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แขวง/ตำบล (*).
        /// </summary>
        public static string SCHOOL_ADDR_TOMBON {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR_TOMBON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสไปรษณีย์.
        /// </summary>
        public static string SCHOOL_ADDR_ZIPCODE {
            get {
                return ResourceManager.GetString("SCHOOL_ADDR_ZIPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล์ (*).
        /// </summary>
        public static string SCHOOL_EMAIL {
            get {
                return ResourceManager.GetString("SCHOOL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อสถานศึกษา (*).
        /// </summary>
        public static string SCHOOL_NAME {
            get {
                return ResourceManager.GetString("SCHOOL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จังหวัด.
        /// </summary>
        public static string SCHOOL_PROVINCE {
            get {
                return ResourceManager.GetString("SCHOOL_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สังกัด (*).
        /// </summary>
        public static string SCHOOL_TYPE {
            get {
                return ResourceManager.GetString("SCHOOL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สพฐ.
        /// </summary>
        public static string SCHOOL_TYPE_01 {
            get {
                return ResourceManager.GetString("SCHOOL_TYPE_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกชน.
        /// </summary>
        public static string SCHOOL_TYPE_02 {
            get {
                return ResourceManager.GetString("SCHOOL_TYPE_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กทม/เทศบาล.
        /// </summary>
        public static string SCHOOL_TYPE_03 {
            get {
                return ResourceManager.GetString("SCHOOL_TYPE_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อุดมศึกษา.
        /// </summary>
        public static string SCHOOL_TYPE_04 {
            get {
                return ResourceManager.GetString("SCHOOL_TYPE_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อื่น ๆ (ระบุ).
        /// </summary>
        public static string SCHOOL_TYPE_OTHER {
            get {
                return ResourceManager.GetString("SCHOOL_TYPE_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เขต.
        /// </summary>
        public static string SCHOOL_ZONE {
            get {
                return ResourceManager.GetString("SCHOOL_ZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เขตพื้นที่การศึกษา.
        /// </summary>
        public static string SCHOOL_ZONE_EDU {
            get {
                return ResourceManager.GetString("SCHOOL_ZONE_EDU", resourceCulture);
            }
        }
    }
}
