//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChinaPhet10Entities : DbContext
    {
        public ChinaPhet10Entities()
            : base("name=ChinaPhet10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_APPLICATION> TB_APPLICATION { get; set; }
        public DbSet<TB_APPLICATION_SCHOOL> TB_APPLICATION_SCHOOL { get; set; }
        public DbSet<TB_APPLICATION_STAFF> TB_APPLICATION_STAFF { get; set; }
        public DbSet<TB_APPLICATION_STUDENT> TB_APPLICATION_STUDENT { get; set; }
        public DbSet<TB_COMMITEE> TB_COMMITEE { get; set; }
        public DbSet<TB_COMMITEE_ROOM> TB_COMMITEE_ROOM { get; set; }
        public DbSet<TB_CONCERN> TB_CONCERN { get; set; }
        public DbSet<TB_EXAM_ABSENT> TB_EXAM_ABSENT { get; set; }
        public DbSet<TB_EXAM_ANOUNCE> TB_EXAM_ANOUNCE { get; set; }
        public DbSet<TB_M_AMPHUR> TB_M_AMPHUR { get; set; }
        public DbSet<TB_M_BUILDING> TB_M_BUILDING { get; set; }
        public DbSet<TB_M_DISTRICT> TB_M_DISTRICT { get; set; }
        public DbSet<TB_M_LEVEL> TB_M_LEVEL { get; set; }
        public DbSet<TB_M_PRIZE> TB_M_PRIZE { get; set; }
        public DbSet<TB_M_PROVINCE> TB_M_PROVINCE { get; set; }
        public DbSet<TB_M_SCHOOL_9> TB_M_SCHOOL_9 { get; set; }
        public DbSet<TB_M_STATUS> TB_M_STATUS { get; set; }
        public DbSet<TB_M_TITLE> TB_M_TITLE { get; set; }
        public DbSet<TB_ROLE> TB_ROLE { get; set; }
        public DbSet<TB_ROLE_PERMISSION> TB_ROLE_PERMISSION { get; set; }
        public DbSet<TB_ROOM> TB_ROOM { get; set; }
        public DbSet<TB_SCHOOL_DOCUMENT> TB_SCHOOL_DOCUMENT { get; set; }
        public DbSet<TB_SCORE_ROUND_1> TB_SCORE_ROUND_1 { get; set; }
        public DbSet<TB_SCORE_ROUND_1_ERROR> TB_SCORE_ROUND_1_ERROR { get; set; }
        public DbSet<TB_SCORE_ROUND_2> TB_SCORE_ROUND_2 { get; set; }
        public DbSet<TB_STUDENT_SEAT> TB_STUDENT_SEAT { get; set; }
        public DbSet<TB_USER> TB_USER { get; set; }
    }
}
