//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_APPLICATION_STUDENT
    {
        public decimal STD_ID { get; set; }
        public Nullable<decimal> STD_TITLE_ID { get; set; }
        public string STD_NAME { get; set; }
        public string STD_SURNAME { get; set; }
        public Nullable<decimal> STD_LEVEL_ID { get; set; }
        public Nullable<decimal> STD_SCHOOL_ID { get; set; }
        public string STD_PICTURE_PATH { get; set; }
        public string STD_PHONE { get; set; }
        public string STD_EMAIL { get; set; }
        public string STD_ID_CARD { get; set; }
        public string STD_PASSPORT_ID { get; set; }
        public Nullable<decimal> STD_GRADE { get; set; }
        public string STD_PHONE_PROVIDER { get; set; }
        public Nullable<decimal> STD_APPROVED_STATUS { get; set; }
        public string STD_BIRTH_DAY { get; set; }
        public string STD_IS_CONCERN { get; set; }
        public Nullable<decimal> STD_NATION { get; set; }
        public string STD_NATION_OTHER { get; set; }
    
        public virtual TB_APPLICATION_SCHOOL TB_APPLICATION_SCHOOL { get; set; }
        public virtual TB_M_LEVEL TB_M_LEVEL { get; set; }
        public virtual TB_M_TITLE TB_M_TITLE { get; set; }
        public virtual TB_M_STATUS TB_M_STATUS { get; set; }
        public virtual TB_STUDENT_SEAT TB_STUDENT_SEAT { get; set; }
    }
}
