//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_APPLICATION
    {
        public decimal PROJECT_ID { get; set; }
        public Nullable<decimal> PROJECT_ROUND { get; set; }
        public Nullable<System.DateTime> PROJECT_REGISTER_START { get; set; }
        public Nullable<System.DateTime> PROJECT_REGISTER_END { get; set; }
        public Nullable<System.DateTime> PROJECT_EXAM_DATE { get; set; }
        public string PROJECT_STATUS { get; set; }
        public Nullable<System.DateTime> PROJECT_ANNOUNCE_DATE { get; set; }
        public Nullable<decimal> PROJECT_IS_ANNOUNCE_ROUND1 { get; set; }
        public Nullable<decimal> PROJECT_IS_ANNOUNCE_ROUND2 { get; set; }
    }
}
