//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_COMMITEE_ROOM
    {
        public decimal COMMITEE_ID { get; set; }
        public Nullable<decimal> COMMITEE_ROOM_ID { get; set; }
    
        public virtual TB_COMMITEE TB_COMMITEE { get; set; }
        public virtual TB_ROOM TB_ROOM { get; set; }
    }
}
