//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_COMMITEE
    {
        public decimal COMMITEE_ID { get; set; }
        public Nullable<decimal> COMMITEE_TITLE_ID { get; set; }
        public string COMMITEE_NAME { get; set; }
        public string COMMITEE_SURNAME { get; set; }
        public string COMMITEE_PHONE { get; set; }
        public string COMMITEE_STATUS { get; set; }
    
        public virtual TB_M_TITLE TB_M_TITLE { get; set; }
        public virtual TB_COMMITEE_ROOM TB_COMMITEE_ROOM { get; set; }
    }
}
