//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_PRIZE
    {
        public TB_M_PRIZE()
        {
            this.TB_SCORE_ROUND_1 = new HashSet<TB_SCORE_ROUND_1>();
            this.TB_SCORE_ROUND_2 = new HashSet<TB_SCORE_ROUND_2>();
        }
    
        public decimal PRIZE_ID { get; set; }
        public string PRIZE_NAME_TH { get; set; }
        public string PRIZE_NAME_EN { get; set; }
        public Nullable<decimal> PRIZE_FOR_ROUND { get; set; }
        public string PRIZE_SCORE_PERIOD { get; set; }
    
        public virtual ICollection<TB_SCORE_ROUND_1> TB_SCORE_ROUND_1 { get; set; }
        public virtual ICollection<TB_SCORE_ROUND_2> TB_SCORE_ROUND_2 { get; set; }
    }
}
