//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_AMPHUR
    {
        public TB_M_AMPHUR()
        {
            this.TB_APPLICATION_SCHOOL = new HashSet<TB_APPLICATION_SCHOOL>();
            this.TB_M_DISTRICT = new HashSet<TB_M_DISTRICT>();
        }
    
        public decimal AMPHUR_ID { get; set; }
        public string AMPHUR_CODE { get; set; }
        public string AMPHUR_NAME { get; set; }
        public Nullable<decimal> GEO_ID { get; set; }
        public Nullable<decimal> PROVINCE_ID { get; set; }
        public string AMPHUR_NAME_ENG { get; set; }
    
        public virtual ICollection<TB_APPLICATION_SCHOOL> TB_APPLICATION_SCHOOL { get; set; }
        public virtual TB_M_PROVINCE TB_M_PROVINCE { get; set; }
        public virtual ICollection<TB_M_DISTRICT> TB_M_DISTRICT { get; set; }
    }
}
