//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_STATUS
    {
        public TB_M_STATUS()
        {
            this.TB_APPLICATION_SCHOOL = new HashSet<TB_APPLICATION_SCHOOL>();
            this.TB_APPLICATION_STUDENT = new HashSet<TB_APPLICATION_STUDENT>();
            this.TB_ROLE = new HashSet<TB_ROLE>();
            this.TB_USER = new HashSet<TB_USER>();
        }
    
        public decimal STATUS_ID { get; set; }
        public string STATUS_NAME_TH { get; set; }
        public Nullable<decimal> STATUS_GROUP { get; set; }
        public string STATUS_NAME_EN { get; set; }
    
        public virtual ICollection<TB_APPLICATION_SCHOOL> TB_APPLICATION_SCHOOL { get; set; }
        public virtual ICollection<TB_APPLICATION_STUDENT> TB_APPLICATION_STUDENT { get; set; }
        public virtual ICollection<TB_ROLE> TB_ROLE { get; set; }
        public virtual ICollection<TB_USER> TB_USER { get; set; }
    }
}
