//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_DISTRICT
    {
        public TB_M_DISTRICT()
        {
            this.TB_APPLICATION_SCHOOL = new HashSet<TB_APPLICATION_SCHOOL>();
        }
    
        public decimal DISTRICT_ID { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT_NAME { get; set; }
        public Nullable<decimal> AMPHUR_ID { get; set; }
        public Nullable<decimal> PROVINCE_ID { get; set; }
        public Nullable<decimal> GEO_ID { get; set; }
        public string DISTRICT_NAME_ENG { get; set; }
    
        public virtual ICollection<TB_APPLICATION_SCHOOL> TB_APPLICATION_SCHOOL { get; set; }
        public virtual TB_M_AMPHUR TB_M_AMPHUR { get; set; }
    }
}
