//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_LEVEL
    {
        public TB_M_LEVEL()
        {
            this.TB_APPLICATION_STAFF = new HashSet<TB_APPLICATION_STAFF>();
            this.TB_APPLICATION_STUDENT = new HashSet<TB_APPLICATION_STUDENT>();
            this.TB_ROOM = new HashSet<TB_ROOM>();
        }
    
        public decimal LEVEL_ID { get; set; }
        public string LEVEL_NAME_TH { get; set; }
        public string LEVEL_NAME_EN { get; set; }
        public string LEVEL_NAME_ZH { get; set; }
    
        public virtual ICollection<TB_APPLICATION_STAFF> TB_APPLICATION_STAFF { get; set; }
        public virtual ICollection<TB_APPLICATION_STUDENT> TB_APPLICATION_STUDENT { get; set; }
        public virtual ICollection<TB_ROOM> TB_ROOM { get; set; }
    }
}
