//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_BUILDING
    {
        public TB_M_BUILDING()
        {
            this.TB_ROOM = new HashSet<TB_ROOM>();
        }
    
        public decimal BUILDING_ID { get; set; }
        public string BUILDING_NAME { get; set; }
    
        public virtual ICollection<TB_ROOM> TB_ROOM { get; set; }
    }
}
