//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ROOM
    {
        public TB_ROOM()
        {
            this.TB_COMMITEE_ROOM = new HashSet<TB_COMMITEE_ROOM>();
            this.TB_STUDENT_SEAT = new HashSet<TB_STUDENT_SEAT>();
        }
    
        public decimal ROOM_ID { get; set; }
        public Nullable<decimal> ROOM_FOR_LEVEL { get; set; }
        public Nullable<decimal> ROOM_BUILD { get; set; }
        public Nullable<decimal> ROOM_FLOOR { get; set; }
        public decimal ROOM_NUMBER { get; set; }
        public Nullable<decimal> ROOM_SEAT_COUNT { get; set; }
        public Nullable<decimal> ROOM_COMMITTEE_COUNT { get; set; }
        public string ROOM_ROW { get; set; }
        public Nullable<decimal> ROW_1 { get; set; }
        public Nullable<decimal> ROW_2 { get; set; }
        public Nullable<decimal> ROW_3 { get; set; }
        public Nullable<decimal> ROW_4 { get; set; }
        public Nullable<decimal> ROW_5 { get; set; }
        public Nullable<decimal> ROW_6 { get; set; }
        public Nullable<decimal> ROW_7 { get; set; }
        public Nullable<decimal> ROW_8 { get; set; }
        public Nullable<decimal> ROW_9 { get; set; }
        public Nullable<decimal> ROW_10 { get; set; }
        public Nullable<decimal> ROW_11 { get; set; }
        public Nullable<decimal> ROW_12 { get; set; }
    
        public virtual ICollection<TB_COMMITEE_ROOM> TB_COMMITEE_ROOM { get; set; }
        public virtual TB_M_BUILDING TB_M_BUILDING { get; set; }
        public virtual TB_M_LEVEL TB_M_LEVEL { get; set; }
        public virtual ICollection<TB_STUDENT_SEAT> TB_STUDENT_SEAT { get; set; }
    }
}
