//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ROLE_PERMISSION
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ROLE_ID { get; set; }
        public string PERMISSION_CODE { get; set; }
    
        public virtual TB_ROLE TB_ROLE { get; set; }
    }
}
