//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SCORE_ROUND_2
    {
        public decimal STD_CODE { get; set; }
        public Nullable<decimal> SCORE_1_11 { get; set; }
        public Nullable<decimal> SCORE_1_12 { get; set; }
        public Nullable<decimal> SCORE_1_13 { get; set; }
        public Nullable<decimal> SCORE_1_14 { get; set; }
        public Nullable<decimal> SCORE_1_15 { get; set; }
        public Nullable<decimal> SCORE_2_21 { get; set; }
        public Nullable<decimal> SCORE_2_22 { get; set; }
        public Nullable<decimal> SCORE_2_23 { get; set; }
        public Nullable<decimal> SCORE_2_24 { get; set; }
        public Nullable<decimal> ROUND_1_SCORE { get; set; }
        public Nullable<decimal> PRIZE_ID { get; set; }
        public Nullable<decimal> SCORE_1_21 { get; set; }
        public Nullable<decimal> SCORE_1_22 { get; set; }
        public Nullable<decimal> SCORE_1_23 { get; set; }
        public Nullable<decimal> SCORE_1_24 { get; set; }
        public Nullable<decimal> SCORE_1_25 { get; set; }
        public Nullable<decimal> SCORE_1_31 { get; set; }
        public Nullable<decimal> SCORE_1_32 { get; set; }
        public Nullable<decimal> SCORE_1_33 { get; set; }
        public Nullable<decimal> SCORE_1_34 { get; set; }
        public Nullable<decimal> SCORE_1_35 { get; set; }
        public Nullable<decimal> SCORE_2_11 { get; set; }
        public Nullable<decimal> SCORE_2_12 { get; set; }
        public Nullable<decimal> SCORE_2_13 { get; set; }
        public Nullable<decimal> SCORE_2_14 { get; set; }
        public Nullable<decimal> SCORE_2_31 { get; set; }
        public Nullable<decimal> SCORE_2_32 { get; set; }
        public Nullable<decimal> SCORE_2_33 { get; set; }
        public Nullable<decimal> SCORE_2_34 { get; set; }
    
        public virtual TB_M_PRIZE TB_M_PRIZE { get; set; }
    }
}
