//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SCORE_ROUND_1_ERROR
    {
        public decimal STD_CODE { get; set; }
        public string STD_NAME { get; set; }
        public Nullable<decimal> STD_SCORE { get; set; }
    }
}
