//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STUDENT_SEAT
    {
        public decimal STUDENT_ID { get; set; }
        public Nullable<decimal> STUDENT_CODE { get; set; }
        public Nullable<decimal> SIT_NUMBER { get; set; }
        public string SIT_NUMBER_PREFIX { get; set; }
        public Nullable<decimal> ROOM_ID { get; set; }
    
        public virtual TB_APPLICATION_STUDENT TB_APPLICATION_STUDENT { get; set; }
        public virtual TB_ROOM TB_ROOM { get; set; }
    }
}
