//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SCHOOL_DOCUMENT
    {
        public Nullable<decimal> SCHOOL_ID { get; set; }
        public string DOCUMENT_PATH { get; set; }
        public decimal ID { get; set; }
    }
}
