//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPUWebPhet10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ROLE_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> CREATE_BY { get; set; }
        public Nullable<System.DateTime> LASTED_LOGIN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual TB_M_STATUS TB_M_STATUS { get; set; }
        public virtual TB_ROLE TB_ROLE { get; set; }
    }
}
